# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11f7fea2a6826e7ca48a51243c4fb7a8932a5fcb548e72d7d340202775770eef81d4e54e5da6c1e2b70ec2047a242e80a76ccbe1e099bf10f99f167d0665a182

test:
  secret_key_base: 78659617e5f1778e67b2834d4a05fd5813e900bc515e80cad3a96b370ad87eea10ff5f9597bb5ef3172da7ec171c97eaf2cffe85d73711d3fdf607b58f38466f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
